name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  preview-back-end:
    name: Create preview back-end
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install yarn
        run: npm install --global yarn

      - name: Install Dependences
        run: |
          cd ./app/web
          yarn install

  preview-front-end:
    name: Create preview back-end
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install yarn
        run: npm install --global yarn

      - name: Install Dependences
        run: |
          cd ./app/web
          yarn install
