name: CD

on:
  workflow_run:
    workflows: [CI]
    types: 
      - completed

jobs:
  preview-back-end:
    name: Create preview back-end
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  preview-front-end:
    name: Create preview back-end
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
